server:
  port: 8080

spring:
  application:
    name: springboot-security-kimseheak
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:  
            scope: profile, email
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: id

mybatis:
  mapper-locations: classpath:mappers/*.xml

jwt:
  issuer: rlatpgur627@gmail.com
  secret_key:  3vCoJJXvpnVEFrF4f0Kgv25Yvwx5mz3Hja/BcI9FWFnWj5QRPmcWFm4uR2UtDnJVPMZc4WPItHVWGraFTYmn1w==
